import './globals.css'
import { Inter } from 'next/font/google'
import { ReactMatrixAnimation } from 'react-matrix-animation'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <div className="bg-matrixBlack min-h-screen">
      <ReactMatrixAnimation />
      {children}
    </div>
  )
}
